/**
 * serve-cli — HTTP serving mode adapter (Phase 12, SERVE-01/SERVE-02).
 *
 * Entry point: `recense serve --db <path>` (dispatched via spawnScript from brain.ts).
 *
 * Exposes two surface protocols on one port (D-01):
 *   REST  — POST /v1/search|add|ask with Phase 11 response shapes (D-04)
 *   MCP   — POST /mcp (stateless MCP-over-HTTP, D-03)
 *   Health — GET /health (unauthenticated, D-13)
 *
 * Auth (SERVE-02): Bearer token required for every path except /health. Token is
 * born on first `recense serve` run (crypto.randomBytes(32)), stored in chmod-600
 * sleep.env as RECENSE_SERVE_TOKEN, printed once, never again (D-05/D-06/D-07).
 *
 * Security invariants:
 *   T-12-03: auth gate fires BEFORE any body parse; identical 401 for absent vs wrong token.
 *   T-12-04: crypto.timingSafeEqual for constant-time comparison; length pre-check guards throw.
 *   T-12-05: token lives only in chmod-600 sleep.env; never in logs or error bodies.
 *   T-12-06: safe-null discipline — raw errors caught, replaced with { error: 'internal_error' }.
 *   T-12-07: 64KB body cap (incremental byte counting, not content-length); requestTimeout=30s.
 *   T-12-08: default bind 127.0.0.1; --host 0.0.0.0 requires explicit opt-in (D-09).
 *   T-12-09: sessionIdGenerator: undefined (stateless); GET /mcp → 405.
 */
import { appendFileSync } from 'fs';
import * as http from 'node:http';
import { timingSafeEqual, randomBytes } from 'node:crypto';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import type { ModelProvider } from '../model/provider';
import { wireMemoryEngine, registerMemoryTools, MemoryBusyError, SurfaceTargetNotFoundError, type MemoryOps } from './memory-ops';
import { resolveExistingEnv, writeEnvFile } from './recense-init';
import { resolveDbPath, sleepEnvPath } from './runtime-config';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const LOG_PATH = '/tmp/recense-serve.log';

/** 64KB body cap (D-11): incremental byte counting — content-length is not trusted. */
const BODY_SIZE_LIMIT = 65_536;

// ---------------------------------------------------------------------------
// Log helpers (D-16: log method, path, status, duration; never bodies, query text, or token)
// ---------------------------------------------------------------------------

/** Append a timestamped line to the log file (never stdout). */
const log = (msg: string): void =>
  appendFileSync(LOG_PATH, `[${new Date().toISOString()}] serve-cli: ${msg}\n`);

/**
 * One-line request log: stdout + LOG_PATH (D-16).
 * NEVER logs request/response bodies, query text, fact values, or the token.
 */
function logRequest(
  method: string,
  urlPath: string,
  status: number,
  durationMs: number,
  authFail?: boolean,
): void {
  const suffix = authFail ? ' auth:fail' : '';
  const line = `${method} ${urlPath} ${status} ${durationMs}ms${suffix}`;
  process.stdout.write(line + '\n');
  appendFileSync(LOG_PATH, `[${new Date().toISOString()}] ${line}\n`);
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface BrainHttpServerOptions {
  // IN-05: no port/host here — the factory returns a NON-LISTENING server; callers
  // (CLI entry and tests) pass port/host to server.listen() themselves. Required-but-
  // ignored options would invite a caller to assume the factory listens.
  dbPath: string;
  /** Already-resolved Bearer token — generated by resolveServeToken() before construction. */
  token: string;
  /** Tests inject MockModelProvider here; omitted → DefaultModelProvider (production). */
  provider?: ModelProvider;
}

export interface BrainHttpServer {
  server: http.Server;
  /** Drain in-flight requests, close MCP transport, close engine and DB handles. */
  close: () => Promise<void>;
}

// ---------------------------------------------------------------------------
// resolveServeToken
// ---------------------------------------------------------------------------

/**
 * Read RECENSE_SERVE_TOKEN from sleep.env (via resolveExistingEnv).
 * If present: return it silently (never print on subsequent runs — Pitfall 5).
 * If absent: generate randomBytes(32).toString('hex'), persist via writeEnvFile
 * (atomic chmod-600), and print EXACTLY ONCE three lines to stdout.
 */
export function resolveServeToken(envPath: string = sleepEnvPath()): string {
  const env = resolveExistingEnv(envPath);
  const existing = env.get('RECENSE_SERVE_TOKEN');
  if (existing) return existing; // already set — silent (Pitfall 5)

  // First run: generate, persist, print once.
  const token = randomBytes(32).toString('hex');
  const vars: Record<string, string> = {};
  for (const [k, v] of env) vars[k] = v;
  vars['RECENSE_SERVE_TOKEN'] = token;
  writeEnvFile(envPath, vars); // atomic chmod-600 write, preserves existing keys/comments

  // T-12-05: print once to stdout for the operator; never to LOG_PATH.
  // WR-06: ONLY on an interactive TTY. Under systemd, stdout IS a persistent log
  // (journald retains it indefinitely, readable by root/adm and included in journal
  // exports) — printing the token there violates the "never in logs" invariant.
  // Non-TTY runs are pointed at sleep.env, the token's canonical chmod-600 home.
  if (process.stdout.isTTY) {
    process.stdout.write('\nrecense serve: token generated.\n');
    process.stdout.write(`  RECENSE_SERVE_TOKEN=${token}\n`);
    process.stdout.write('  Record this token — it will NOT be printed again.\n\n');
  } else {
    process.stdout.write(
      `\nrecense serve: token generated and stored in ${envPath} ` +
      `(not printed — stdout is not a TTY; read it with: grep '^RECENSE_SERVE_TOKEN=' ${envPath})\n\n`,
    );
  }
  return token;
}

// ---------------------------------------------------------------------------
// checkAuth — constant-time Bearer token comparison (T-12-03/T-12-04)
// ---------------------------------------------------------------------------

/**
 * Verify the Authorization: Bearer header against the stored token.
 * Fires BEFORE any body parse (T-12-03). Returns false for:
 *   - absent or non-Bearer Authorization header
 *   - wrong token length (prevents timingSafeEqual throw — Pitfall 2)
 *   - mismatched token (timingSafeEqual constant-time compare)
 * Both absent-header and wrong-token paths return the identical 401 body (no enumeration).
 */
function checkAuth(req: http.IncomingMessage, storedToken: string): boolean {
  const header = req.headers['authorization'] ?? '';
  if (!header.startsWith('Bearer ')) return false;
  const provided = header.slice('Bearer '.length);
  // T-12-04: token length is a fixed 64-char hex (not secret); pre-check prevents the
  // Node.js ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH throw from leaking as a 500 (Pitfall 2).
  if (provided.length !== storedToken.length) return false;
  try {
    return timingSafeEqual(Buffer.from(provided, 'utf8'), Buffer.from(storedToken, 'utf8'));
  } catch {
    return false; // belt-and-suspenders for unexpected encoding errors
  }
}

// ---------------------------------------------------------------------------
// readBody — incremental body read with 64KB cap (T-12-07)
// ---------------------------------------------------------------------------

/**
 * Accumulate the request body; resolve null if the cap is exceeded (caller sends 413).
 * NEVER trusts content-length (it is caller-controlled — Pitfall in RESEARCH.md).
 *
 * IMPORTANT: does NOT call req.destroy() on overflow — destroying the socket before
 * the handler writes the 413 response would kill the socket and the 413 would never
 * reach the client. Instead we stop accumulating and resolve null; the handler sends
 * 413 normally. The remaining oversized data is drained and discarded by Node.js after
 * res.end(), which also signals connection close (HTTP/1.1 default).
 */
function readBody(req: http.IncomingMessage): Promise<string | null> {
  return new Promise((resolve, reject) => {
    // CR-02: accumulate raw buffers and decode ONCE at the end. Decoding each chunk
    // independently (`chunk.toString('utf8')`) replaces any multibyte UTF-8 sequence
    // that straddles a TCP chunk boundary with U+FFFD — silently corrupting non-ASCII
    // content that then parses as valid JSON and gets persisted as a memory episode.
    const chunks: Buffer[] = [];
    let size = 0;
    let settled = false;
    req.on('data', (chunk: Buffer) => {
      if (settled) return; // discard data after overflow; let socket drain naturally
      size += chunk.length; // byte counting stays on raw chunk length (T-12-07)
      if (size > BODY_SIZE_LIMIT) {
        settled = true;
        resolve(null); // null → 413 from the caller
        return;
      }
      chunks.push(chunk);
    });
    req.on('end', () => {
      if (!settled) { settled = true; resolve(Buffer.concat(chunks).toString('utf8')); }
    });
    req.on('error', (err) => { if (!settled) { settled = true; reject(err); } });
  });
}

// ---------------------------------------------------------------------------
// json helpers
// ---------------------------------------------------------------------------

function jsonOk(res: http.ServerResponse, body: unknown): void {
  const payload = JSON.stringify(body);
  res.writeHead(200, { 'content-type': 'application/json' });
  res.end(payload);
}

function jsonError(res: http.ServerResponse, status: number, body: unknown): void {
  const payload = JSON.stringify(body);
  res.writeHead(status, { 'content-type': 'application/json' });
  res.end(payload);
}

// ---------------------------------------------------------------------------
// buildMcpServer — per-request McpServer construction (WR-03)
// ---------------------------------------------------------------------------

/**
 * Construct a fresh McpServer with the three memory tools registered.
 *
 * WR-03: the stateless StreamableHTTPServerTransport tracks in-flight
 * request→response mappings keyed by JSON-RPC request id, so the SDK requires a
 * NEW server + transport per request (see the SDK's simpleStatelessStreamableHttp
 * example) — a shared instance misroutes/drops responses when concurrent clients
 * reuse ids (two independent clients both starting at id 1 is the normal case).
 * The engine/ops stay shared (D-02); only this cheap MCP wrapper is per-request.
 */
function buildMcpServer(ops: MemoryOps): McpServer {
  const mcpServer = new McpServer(
    { name: 'recense', version: '0.1.0' },
    {
      instructions:
        'recense tools: memory_search (LLM-free semantic retrieval), memory_add ' +
        '(record a fact/observation), memory_ask (question answering over memory). ' +
        'Writes land as episodes; abstraction/consolidation runs in the hourly sleep pass, not inline.',
    },
  );
  // Register the same three tools as the stdio MCP surface (same ops → one engine instance, D-02).
  registerMemoryTools(mcpServer, ops);
  return mcpServer;
}

// ---------------------------------------------------------------------------
// createBrainHttpServer — factory (D-01/D-02)
// ---------------------------------------------------------------------------

/**
 * Build the brain HTTP server: wire the shared memory-ops core, construct the MCP
 * server + stateless transport, and return an http.Server that is NOT yet listening.
 * Callers (CLI entry and tests) call server.listen() themselves.
 *
 * Design: factory-exported so tests can inject token + MockModelProvider without
 * any subprocess or env-file access (same pattern as createBrainMcpServer).
 */
export async function createBrainHttpServer(
  opts: BrainHttpServerOptions,
): Promise<BrainHttpServer> {
  // ── 1. Wire shared memory-ops core (D-02: one engine, one source tag 'http') ──
  // separateReadHandle: true → search path uses its own read-only DB handle (criterion 4).
  const { ops, close: closeEngine } = await wireMemoryEngine({
    dbPath: opts.dbPath,
    provider: opts.provider,
    source: 'http',
    separateReadHandle: true,
  });

  // ── 2. MCP server + transport are created PER REQUEST in the /mcp handler (WR-03) ──

  // ── 3. Read package.json version for /health (fallback to '0.1.0') ─────────
  let pkgVersion = '0.1.0';
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    pkgVersion = (require('../../package.json') as { version: string }).version ?? '0.1.0';
  } catch { /* fallback */ }

  // ── 4. Request handler ──────────────────────────────────────────────────────
  const requestHandler = async (req: http.IncomingMessage, res: http.ServerResponse): Promise<void> => {
    const start = Date.now();
    const url = (req.url ?? '/').split('?')[0]!;

    // ── /health — unauthenticated (D-13); MUST appear before the auth gate ──
    if (url === '/health' && req.method === 'GET') {
      jsonOk(res, { status: 'ok', version: pkgVersion });
      logRequest('GET', '/health', 200, Date.now() - start);
      return;
    }

    // ── Auth gate — fires for ALL other paths BEFORE any body read (T-12-03) ──
    if (!checkAuth(req, opts.token)) {
      jsonError(res, 401, { error: 'unauthorized' });
      logRequest(req.method ?? 'UNKNOWN', url, 401, Date.now() - start, true);
      return;
    }

    // ── Authenticated routes ────────────────────────────────────────────────

    // POST /v1/search — LLM-free read path (no lock; separate read handle via shared core)
    if (url === '/v1/search' && req.method === 'POST') {
      const rawBody = await readBody(req);
      if (rawBody === null) {
        jsonError(res, 413, { error: 'payload_too_large' });
        logRequest('POST', url, 413, Date.now() - start);
        return;
      }
      let parsed: { query?: unknown };
      try { parsed = JSON.parse(rawBody) as { query?: unknown }; } catch {
        jsonError(res, 400, { error: 'bad_request', detail: 'invalid json' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      if (typeof parsed.query !== 'string') {
        jsonError(res, 400, { error: 'bad_request', detail: 'missing required field: query' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      try {
        const results = await ops.search(parsed.query);
        jsonOk(res, { results });
        logRequest('POST', url, 200, Date.now() - start);
      } catch (err) {
        log(`/v1/search error: ${err}`);
        jsonError(res, 500, { error: 'internal_error' });
        logRequest('POST', url, 500, Date.now() - start);
      }
      return;
    }

    // POST /v1/add — episodic write; per-call lock (T-12-02)
    if (url === '/v1/add' && req.method === 'POST') {
      const rawBody = await readBody(req);
      if (rawBody === null) {
        jsonError(res, 413, { error: 'payload_too_large' });
        logRequest('POST', url, 413, Date.now() - start);
        return;
      }
      let parsed: { content?: unknown; origin?: unknown };
      try { parsed = JSON.parse(rawBody) as { content?: unknown; origin?: unknown }; } catch {
        jsonError(res, 400, { error: 'bad_request', detail: 'invalid json' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      if (typeof parsed.content !== 'string') {
        jsonError(res, 400, { error: 'bad_request', detail: 'missing required field: content' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      const origin = typeof parsed.origin === 'string' ? parsed.origin : undefined;
      try {
        const ack = await ops.add(parsed.content, origin);
        jsonOk(res, ack);
        logRequest('POST', url, 200, Date.now() - start);
      } catch (err) {
        if (err instanceof MemoryBusyError) {
          jsonError(res, 503, { error: 'service_unavailable', detail: 'memory busy; retry in a moment' });
          logRequest('POST', url, 503, Date.now() - start);
          return;
        }
        log(`/v1/add error: ${err}`);
        jsonError(res, 500, { error: 'internal_error' });
        logRequest('POST', url, 500, Date.now() - start);
      }
      return;
    }

    // POST /v1/ask — HybridResponder; per-call lock (T-12-02)
    if (url === '/v1/ask' && req.method === 'POST') {
      const rawBody = await readBody(req);
      if (rawBody === null) {
        jsonError(res, 413, { error: 'payload_too_large' });
        logRequest('POST', url, 413, Date.now() - start);
        return;
      }
      let parsed: { query?: unknown };
      try { parsed = JSON.parse(rawBody) as { query?: unknown }; } catch {
        jsonError(res, 400, { error: 'bad_request', detail: 'invalid json' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      if (typeof parsed.query !== 'string') {
        jsonError(res, 400, { error: 'bad_request', detail: 'missing required field: query' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      try {
        const out = await ops.ask(parsed.query);
        jsonOk(res, { answer: out.answer, origin: out.origin });
        logRequest('POST', url, 200, Date.now() - start);
      } catch (err) {
        if (err instanceof MemoryBusyError) {
          jsonError(res, 503, { error: 'service_unavailable', detail: 'memory busy; retry in a moment' });
          logRequest('POST', url, 503, Date.now() - start);
          return;
        }
        log(`/v1/ask error: ${err}`);
        jsonError(res, 500, { error: 'internal_error' });
        logRequest('POST', url, 500, Date.now() - start);
      }
      return;
    }

    // GET /v1/surface — LLM-free ranked surface items; lock-free read (D-95, T-12-02 N/A)
    if (url === '/v1/surface' && req.method === 'GET') {
      try {
        // url has query stripped — read params from req.url directly (serve-cli.ts 276).
        const sp = new URL(req.url ?? '/', 'http://x').searchParams;
        const surfaceOpts: { maxNonP0?: number; gracePeriodMs?: number } = {};
        // WR-03: `limit` tunes the D-09 non-P0 rolling cap (maxNonP0), NOT a total
        // response-size limit — P0 items always bypass the cap (surface-store.ts), so the
        // response is never bounded below the P0 count. Clamp to a sane ceiling so a caller
        // passing e.g. ?limit=1000000 cannot effectively disable the cap and pull every
        // lower-tier row.
        const limitRaw = sp.get('limit');
        if (limitRaw !== null) {
          const n = Number(limitRaw);
          if (Number.isFinite(n) && n > 0) surfaceOpts.maxNonP0 = Math.min(Math.floor(n), 50);
        }
        const graceRaw = sp.get('grace_hours');
        if (graceRaw !== null) {
          const h = Number(graceRaw);
          if (Number.isFinite(h) && h >= 0) surfaceOpts.gracePeriodMs = h * 60 * 60 * 1000;
        }
        const items = await ops.surface(Object.keys(surfaceOpts).length > 0 ? surfaceOpts : undefined);
        jsonOk(res, { items });
        logRequest('GET', url, 200, Date.now() - start);
      } catch (err) {
        log(`/v1/surface error: ${err}`);
        jsonError(res, 500, { error: 'internal_error' });
        logRequest('GET', url, 500, Date.now() - start);
      }
      return;
    }

    // POST /v1/surface/seen — record outcome; per-call lock (T-12-02)
    if (url === '/v1/surface/seen' && req.method === 'POST') {
      const rawBody = await readBody(req);
      if (rawBody === null) {
        jsonError(res, 413, { error: 'payload_too_large' });
        logRequest('POST', url, 413, Date.now() - start);
        return;
      }
      let parsed: { node_id?: unknown; occurrence_due_at?: unknown; outcome?: unknown; snooze_until?: unknown };
      try { parsed = JSON.parse(rawBody) as typeof parsed; } catch {
        jsonError(res, 400, { error: 'bad_request', detail: 'invalid json' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      // T-21-07: validate all fields before any write
      if (typeof parsed.node_id !== 'string' || typeof parsed.occurrence_due_at !== 'string') {
        jsonError(res, 400, { error: 'bad_request', detail: 'node_id and occurrence_due_at must be strings' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      if (Number.isNaN(Date.parse(parsed.occurrence_due_at))) {
        jsonError(res, 400, { error: 'bad_request', detail: 'occurrence_due_at is not a valid date' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      const VALID_OUTCOMES = ['surfaced', 'seen', 'snoozed', 'completed', 'dismissed'] as const;
      type ValidOutcome = typeof VALID_OUTCOMES[number];
      if (parsed.outcome !== undefined &&
          (typeof parsed.outcome !== 'string' || !VALID_OUTCOMES.includes(parsed.outcome as ValidOutcome))) {
        jsonError(res, 400, { error: 'bad_request', detail: 'outcome must be one of: surfaced, seen, snoozed, completed, dismissed' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      if (parsed.snooze_until !== undefined && parsed.snooze_until !== null &&
          (typeof parsed.snooze_until !== 'string' || Number.isNaN(Date.parse(parsed.snooze_until)))) {
        jsonError(res, 400, { error: 'bad_request', detail: 'snooze_until is not a valid date' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      // WR-01: enforce the documented contract (SurfaceSeenParams.snooze_until: "required
      // when outcome = 'snoozed'"). Without a future snooze_until, isExcluded() takes the
      // `null !== null → false` branch and the item is never excluded — a silent no-op snooze
      // that keeps re-surfacing (repeated unwanted Phase-22 push notifications). Fail fast.
      if (parsed.outcome === 'snoozed' &&
          (typeof parsed.snooze_until !== 'string' || Number.isNaN(Date.parse(parsed.snooze_until)))) {
        jsonError(res, 400, { error: 'bad_request', detail: "snooze_until is required when outcome='snoozed'" });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      const snoozeUntil = parsed.snooze_until === null ? null :
        typeof parsed.snooze_until === 'string' ? parsed.snooze_until :
        undefined;
      try {
        const ack = await ops.surfaceSeen({
          node_id:           parsed.node_id,
          occurrence_due_at: parsed.occurrence_due_at,
          outcome:           parsed.outcome as ValidOutcome | undefined,
          snooze_until:      snoozeUntil,
        });
        jsonOk(res, ack);
        logRequest('POST', url, 200, Date.now() - start);
      } catch (err) {
        if (err instanceof MemoryBusyError) {
          jsonError(res, 503, { error: 'service_unavailable', detail: 'memory busy; retry in a moment' });
          logRequest('POST', url, 503, Date.now() - start);
          return;
        }
        if (err instanceof SurfaceTargetNotFoundError) {
          jsonError(res, 404, { error: 'not_found', detail: 'node_id does not exist' });
          logRequest('POST', url, 404, Date.now() - start);
          return;
        }
        log(`/v1/surface/seen error: ${err}`);
        jsonError(res, 500, { error: 'internal_error' });
        logRequest('POST', url, 500, Date.now() - start);
      }
      return;
    }

    // POST /mcp — stateless MCP-over-HTTP (D-03, T-12-09)
    // Do NOT log the JSON-RPC body (T-12-05 / D-16).
    if (url === '/mcp' && req.method === 'POST') {
      const rawBody = await readBody(req);
      if (rawBody === null) {
        jsonError(res, 413, { error: 'payload_too_large' });
        logRequest('POST', url, 413, Date.now() - start);
        return;
      }
      let parsedBody: unknown;
      try { parsedBody = JSON.parse(rawBody); } catch {
        jsonError(res, 400, { error: 'bad_request', detail: 'invalid json' });
        logRequest('POST', url, 400, Date.now() - start);
        return;
      }
      // The transport handles JSON-RPC parsing, method dispatch, and the response.
      // Status/duration logging after handleRequest returns (transport writes the response).
      try {
        // WR-03: fresh McpServer + transport per request — stateless mode requires it.
        // T-12-09: sessionIdGenerator: undefined → stateless; no Mcp-Session-Id lifecycle.
        // enableJsonResponse: true → direct application/json response instead of an SSE
        // stream (more suitable for REST-style callers — Tonos, curl). The Accept header
        // must still include both application/json and text/event-stream per the SDK spec.
        const mcpServer = buildMcpServer(ops);
        const mcpTransport = new StreamableHTTPServerTransport({
          sessionIdGenerator: undefined,
          enableJsonResponse: true,
        });
        res.on('close', () => { void mcpTransport.close(); void mcpServer.close(); });
        await mcpServer.connect(mcpTransport);
        await mcpTransport.handleRequest(req, res, parsedBody);
        logRequest('POST', url, res.statusCode ?? 200, Date.now() - start);
      } catch (err) {
        log(`/mcp handleRequest error: ${err}`);
        if (!res.headersSent) {
          jsonError(res, 500, { error: 'internal_error' });
        }
        logRequest('POST', url, 500, Date.now() - start);
      }
      return;
    }

    // GET /mcp → 405 (T-12-09: stateless mode has no SSE push channel; Pitfall 4)
    if (url === '/mcp' && req.method === 'GET') {
      jsonError(res, 405, { error: 'method_not_allowed' });
      logRequest('GET', url, 405, Date.now() - start);
      return;
    }

    // ── 404 catch-all ────────────────────────────────────────────────────────
    jsonError(res, 404, { error: 'not_found' });
    logRequest(req.method ?? 'UNKNOWN', url, 404, Date.now() - start);
  };

  // ── 5. Build http.Server with timeouts (Pattern 8, D-11) ───────────────────
  const server = http.createServer((req, res) => {
    requestHandler(req, res).catch(err => {
      log(`unhandled handler error: ${err}`);
      if (!res.headersSent) {
        jsonError(res, 500, { error: 'internal_error' });
      }
    });
  });

  // T-12-07: sane timeouts for slow clients.
  // server.timeout stays at default (0 = no inactivity timeout) — MCP may hold connections.
  server.requestTimeout = 30_000;  // 30s: drop connections that don't complete a request
  server.headersTimeout = 15_000;  // 15s: drop connections that don't finish headers

  // ── 6. close() — drain server → close engine ───────────────────────────────
  // (No shared MCP transport to close — per-request transports close on res 'close', WR-03.)
  async function close(): Promise<void> {
    await new Promise<void>(r => server.close(() => r()));
    closeEngine();
  }

  return { server, close };
}

// ─── CLI entry point — fires ONLY when spawned as the main module ─────────────
if (require.main === module) {
  (async () => {
    // T-11-04 pattern: explicit DB path required — never silently open a default DB.
    const dbPath = resolveDbPath(process.argv, { fallbackToDefault: false });
    if (!dbPath) {
      // WR-02: a long-running server must fail LOUDLY on misconfiguration. Exit-0 with
      // log-file-only output is the hook convention; under systemd (Restart=on-failure)
      // it meant silent service death with nothing in journalctl.
      process.stderr.write('recense serve: no DB path supplied (--db <path> or RECENSE_DB) — exiting\n');
      log('No DB path supplied (--db <path> or RECENSE_DB env var) — exiting');
      process.exit(1);
    }

    // Generate or read token (first run: print once; subsequent runs: silent).
    const token = resolveServeToken();

    // Parse --port (default 7701) and --host (default '127.0.0.1') from argv.
    // IN-10: an invalid --port must fail loudly — `parseInt(...) || 7701` silently
    // mapped typos (`--port abc`, a missing value, `--port 0`) to the default port.
    let port = 7701;
    const portIdx = process.argv.indexOf('--port');
    if (portIdx !== -1) {
      const raw = process.argv[portIdx + 1];
      const parsed = Number(raw);
      if (!raw || !Number.isInteger(parsed) || parsed < 1 || parsed > 65535) {
        process.stderr.write(`recense serve: invalid --port value '${raw ?? ''}' — expected an integer between 1 and 65535\n`);
        process.exit(1);
      }
      port = parsed;
    }

    const hostIdx = process.argv.indexOf('--host');
    const host = hostIdx !== -1 ? (process.argv[hostIdx + 1] ?? '127.0.0.1') : '127.0.0.1';

    const { server, close } = await createBrainHttpServer({ dbPath, token });

    server.listen(port, host, () => {
      process.stdout.write(`recense serve: listening on http://${host}:${port}\n`);
    });

    // Pitfall 6: async drain before exit — never synchronous process.exit without close().
    const shutdown = () => {
      close().then(() => process.exit(0)).catch(() => process.exit(1));
    };
    process.on('SIGTERM', shutdown);
    process.on('SIGINT', shutdown);
  })().catch(err => {
    appendFileSync(LOG_PATH, `[${new Date().toISOString()}] serve-cli FATAL: ${err}\n`);
    process.exit(1);
  });
}
