/**
 * EpisodicStore — unconditional append-only episodic log (INGEST-01).
 *
 * Invariants enforced here:
 *  - Every call to append() inserts exactly one row (nothing is ever dropped).
 *  - Content is capped at config.maxContentBytes with a truncation marker (D-09).
 *  - ts is always taken from the injected clock — never Date.now() (D-12).
 *  - id is a UUID v4 generated by newId().
 *  - consolidated starts at 0; the sleep pass is the only writer that sets it to 1.
 *  - All SQL uses parameterized statements (T-02-SQL).
 *
 * Separation of concerns:
 *  - This store does NOT score episodes; salience + hard_keep arrive as AppendEventParams.
 *  - Scoring lives exclusively in AllocationGate (INGEST-02).
 */
import Database from 'better-sqlite3';
import { utimesSync, openSync, closeSync } from 'fs';
import { newId } from '../lib/hash';
import type { Clock } from '../lib/clock';
import type { EngineConfig } from '../lib/config';
import type { EpisodeRow, EpisodeRole, Origin } from '../lib/types';

/** Parameters accepted by EpisodicStore.append(). */
export interface AppendEventParams {
  content: string;
  origin: Origin;
  /** Heuristic salience [0,1] — computed by AllocationGate (D-03). */
  salience: number;
  /** SQLite bool 0|1 — computed by AllocationGate (D-03). */
  hard_keep: number;
  role: EpisodeRole;
  session_id: string;
  source_inference_id?: string | null;
  /** Channel that produced this episode — D-57. Defaults to 'claude-code' (back-compat). */
  source?: string;
  /** Per-source dedup key — D-59. Null means no dedup (each append is distinct). Defaults to null. */
  external_id?: string | null;
  /**
   * Working directory of the Claude Code session (DEBT-06). Defaults to '' (global/cross-project).
   * Email and other non-hook episodes leave this empty — they are always globally visible.
   */
  cwd?: string;
  /**
   * Optional timestamp override (milliseconds since epoch). EVAL USE ONLY.
   * When provided, the episode is stored with this ts instead of clock.nowMs().
   * Production code paths must never set this field — they rely on the injected
   * clock (D-12). The eval harness uses it to preserve the historical ordering of
   * haystack sessions so temporal-reasoning questions are scored correctly.
   * Defaults to undefined (falls back to clock.nowMs()).
   */
  ts?: number;
}

/** Truncation marker appended when content exceeds maxContentBytes (D-09). */
const TRUNCATION_MARKER = '…[truncated]'; // '…[truncated]'

/**
 * Cap `content` to at most `maxBytes` UTF-8 bytes, appending a truncation marker.
 * If content already fits, returns it unchanged.
 * Byte budget: the stored content satisfies
 *   Buffer.byteLength(result) <= maxBytes + Buffer.byteLength(TRUNCATION_MARKER)
 */
function capContent(content: string, maxBytes: number): string {
  if (Buffer.byteLength(content, 'utf8') <= maxBytes) return content;
  // Slice to maxBytes bytes then decode — UTF-8 boundary may leave a partial
  // multi-byte sequence at the end; toString('utf8') replaces it with U+FFFD.
  const truncated = Buffer.from(content, 'utf8').subarray(0, maxBytes).toString('utf8');
  return truncated + TRUNCATION_MARKER;
}

export class EpisodicStore {
  private readonly db: Database.Database;
  private readonly clock: Clock;
  private readonly config: EngineConfig;

  // Prepared statements — compiled once in constructor (never per-call)
  private readonly stmtInsert: Database.Statement;
  private readonly stmtListUnconsolidated: Database.Statement;
  private readonly stmtGetById: Database.Statement;
  /**
   * The sleep pass is the sole writer of episode.consolidated (CONSOL-02/03).
   * Called inside the per-episode transaction so a killed/restarted pass never
   * double-applies strength increments (resumable checkpoint).
   */
  private readonly stmtMarkConsolidated: Database.Statement;
  /**
   * Echo-detection primitives (D-44/D-45) — offline-pass-only.
   * backfillSourceInferenceId is the sole post-capture writer of source_inference_id;
   * the consolidator calls it BEFORE building ClaimDecision so the existing guard
   * (consolidator.ts episodeSourceInferenceId === null) excludes echoes for free.
   */
  private readonly stmtListRecentInferred: Database.Statement;
  private readonly stmtBackfillSourceInferenceId: Database.Statement;
  /**
   * Dedup backstop (D-59): look up an existing row by (source, external_id).
   * Called only when INSERT OR IGNORE reports 0 changes (non-null external_id dedup hit).
   */
  private readonly stmtGetBySourceExternal: Database.Statement;

  constructor(db: Database.Database, clock: Clock, config: EngineConfig) {
    this.db = db;
    this.clock = clock;
    this.config = config;

    // ── Prepared statements (all use ? / @named — T-02-SQL) ──────────────────

    // INSERT OR IGNORE: when external_id is non-null and (source, external_id) already
    // exists, the UNIQUE index fires → 0 rows inserted → dedup branch in append() (D-59).
    // When external_id is null, the unique index treats each NULL as distinct, so legacy
    // claude-code rows always insert (INGEST-01 unconditional append preserved).
    this.stmtInsert = db.prepare(`
      INSERT OR IGNORE INTO episode (
        id, ts, content, origin, salience, hard_keep,
        consolidated, source_inference_id, role, session_id,
        source, external_id, cwd
      ) VALUES (
        @id, @ts, @content, @origin, @salience, @hard_keep,
        0, @source_inference_id, @role, @session_id,
        @source, @external_id, @cwd
      )
    `);

    // D-03 / D-10: replay priority — hard_keep first, then salience descending
    this.stmtListUnconsolidated = db.prepare(
      'SELECT * FROM episode WHERE consolidated = 0 ORDER BY hard_keep DESC, salience DESC',
    );

    this.stmtGetById = db.prepare('SELECT * FROM episode WHERE id = ?');

    // CONSOL-02/03: sole writer of episode.consolidated; called inside each episode's transaction
    this.stmtMarkConsolidated = db.prepare(
      'UPDATE episode SET consolidated = 1 WHERE id = ?'
    );

    // D-44/D-45: echo-detection primitives — offline pass only (T-02-SQL: bound ? params)
    // listRecentInferred: sorted newest-first so the consolidator's linear scan finds the
    // best match from the freshest inferences, consistent with the recency-window intent.
    this.stmtListRecentInferred = db.prepare(
      "SELECT * FROM episode WHERE origin = 'inferred' AND ts >= ? ORDER BY ts DESC",
    );
    // backfillSourceInferenceId: safe UPDATE — no-op if id does not exist (single-writer,
    // offline-pass-only; this is the only post-capture writer of source_inference_id).
    // Reinterprets the Phase-3 capture-time null as a consolidation-time backfill (D-44).
    this.stmtBackfillSourceInferenceId = db.prepare(
      'UPDATE episode SET source_inference_id = ? WHERE id = ?',
    );

    // D-59 dedup backstop: return the pre-existing row when INSERT OR IGNORE fires.
    // Only reachable when external_id IS NOT NULL — null rows are always distinct.
    this.stmtGetBySourceExternal = db.prepare(
      'SELECT * FROM episode WHERE source = ? AND external_id = ?',
    );
  }

  /**
   * Touch the dirty-sentinel file (L8N-01) to signal that a new episode was written.
   * launchd WatchPaths watches this file and runs the sleep-pass wrapper within seconds.
   *
   * Design invariants:
   *  - No-op when config.dirtySentinelPath is empty/undefined (default OFF).
   *  - Synchronous, sub-millisecond — NEVER throws or awaits (CLAUDE.md: online write
   *    path stays fast and LLM-free; never block the write).
   *  - Swallows ALL errors via a double-layer try/catch.
   *  - Strategy: utimesSync first (fast mtime bump if file exists); on ENOENT fall back
   *    to closeSync(openSync(path, 'a')) to create the file.
   */
  private touchDirtySentinel(): void {
    const sentinelPath = this.config.dirtySentinelPath;
    if (!sentinelPath) return;
    const now = new Date();
    try {
      utimesSync(sentinelPath, now, now);
    } catch {
      // File doesn't exist yet — create it
      try {
        closeSync(openSync(sentinelPath, 'a'));
      } catch {
        // Swallow all errors — never throw into append()
      }
    }
  }

  /**
   * Insert one episode row and return it. Idempotent on (source, external_id) when
   * external_id is non-null — a second call with the same pair returns the original row
   * without inserting a duplicate (D-59 dedup backstop). When external_id is null (legacy
   * claude-code episodes) every call inserts unconditionally (INGEST-01 preserved).
   * Content is capped at config.maxContentBytes with a truncation marker (D-09).
   * ts is taken from clock.nowMs() — never Date.now() (D-12).
   */
  append(params: AppendEventParams): EpisodeRow {
    const id = newId();
    // params.ts is an EVAL-only override; production callers never set it (D-12).
    const ts = params.ts != null ? params.ts : this.clock.nowMs();
    const content = capContent(params.content, this.config.maxContentBytes);
    const source = params.source ?? 'claude-code';
    const external_id = params.external_id ?? null;
    const cwd = params.cwd ?? '';

    const info = this.stmtInsert.run({
      id,
      ts,
      content,
      origin: params.origin,
      salience: params.salience,
      hard_keep: params.hard_keep,
      source_inference_id: params.source_inference_id ?? null,
      role: params.role,
      session_id: params.session_id,
      source,
      external_id,
      cwd,
    });

    // Dedup hit: INSERT OR IGNORE fired (0 rows changed) and external_id is non-null.
    // Return the pre-existing row so the caller receives a valid EpisodeRow (not undefined).
    if (info.changes === 0 && external_id !== null) {
      return this.stmtGetBySourceExternal.get(source, external_id) as EpisodeRow;
    }

    // Real new insert (info.changes === 1). Touch the dirty-sentinel to trigger the
    // sleep pass via launchd WatchPaths, UNLESS this is an inferred episode (D-43:
    // inferred episodes never consolidate — must not trigger a consolidation pass).
    if (params.origin !== 'inferred') {
      this.touchDirtySentinel();
    }

    // Normal path: return the freshly inserted row.
    return this.stmtGetById.get(id) as EpisodeRow;
  }

  /**
   * All episodes not yet processed by the sleep pass, in replay-priority order:
   *   hard_keep DESC, then salience DESC (D-03 / D-10).
   * Leverages idx_episode_unconsolidated index.
   */
  listUnconsolidated(): EpisodeRow[] {
    return this.stmtListUnconsolidated.all() as EpisodeRow[];
  }

  /**
   * Retrieve a single episode by id.
   * Returns null if the id does not exist.
   */
  getEpisode(id: string): EpisodeRow | null {
    const row = this.stmtGetById.get(id) as EpisodeRow | undefined;
    return row ?? null;
  }

  /**
   * Mark an episode as consolidated (consolidated = 1).
   * SOLE WRITER of episode.consolidated — only the sleep pass calls this (CONSOL-02/03).
   * Must be called inside the same db.transaction as the episode's strength/graph effects
   * so a killed/restarted pass never double-applies a strength increment.
   */
  markConsolidated(id: string): void {
    this.stmtMarkConsolidated.run(id);
  }

  /**
   * Return all inferred-origin episodes with ts >= sinceMs, newest first.
   * Used by the consolidator's echo-detection step (D-44/D-45) to find recent
   * inferences within the echoRecencyWindowMs.
   */
  listRecentInferred(sinceMs: number): EpisodeRow[] {
    return this.stmtListRecentInferred.all(sinceMs) as EpisodeRow[];
  }

  /**
   * Backfill source_inference_id on an existing episode.
   *
   * OFFLINE-PASS-ONLY — the Consolidator's detectEcho step is the sole caller (D-44).
   * Reinterprets the Phase-3 capture-time null as a consolidation-time backfill:
   * the inference is logged as an inferred-origin episode at recall time (D-43), and
   * echoes are recognised only during the next sleep pass (D-44) — intentional, not a bug.
   *
   * Safe UPDATE: if episodeId does not exist, 0 rows are affected (no-op).
   */
  backfillSourceInferenceId(episodeId: string, sourceId: string): void {
    this.stmtBackfillSourceInferenceId.run(sourceId, episodeId);
  }
}
