/**
 * EpisodicStore — unconditional append-only episodic log (INGEST-01).
 *
 * Invariants enforced here:
 *  - Every call to append() inserts exactly one row (nothing is ever dropped).
 *  - Content is capped at config.maxContentBytes with a truncation marker (D-09).
 *  - ts is always taken from the injected clock — never Date.now() (D-12).
 *  - id is a UUID v4 generated by newId().
 *  - consolidated starts at 0; the sleep pass is the only writer that sets it to 1.
 *  - All SQL uses parameterized statements (T-02-SQL).
 *
 * Separation of concerns:
 *  - This store does NOT score episodes; salience + hard_keep arrive as AppendEventParams.
 *  - Scoring lives exclusively in AllocationGate (INGEST-02).
 */
import Database from 'better-sqlite3';
import { newId } from '../lib/hash';
import type { Clock } from '../lib/clock';
import type { EngineConfig } from '../lib/config';
import type { EpisodeRow, EpisodeRole, Origin } from '../lib/types';

/** Parameters accepted by EpisodicStore.append(). */
export interface AppendEventParams {
  content: string;
  origin: Origin;
  /** Heuristic salience [0,1] — computed by AllocationGate (D-03). */
  salience: number;
  /** SQLite bool 0|1 — computed by AllocationGate (D-03). */
  hard_keep: number;
  role: EpisodeRole;
  session_id: string;
  source_inference_id?: string | null;
}

/** Truncation marker appended when content exceeds maxContentBytes (D-09). */
const TRUNCATION_MARKER = '…[truncated]'; // '…[truncated]'

/**
 * Cap `content` to at most `maxBytes` UTF-8 bytes, appending a truncation marker.
 * If content already fits, returns it unchanged.
 * Byte budget: the stored content satisfies
 *   Buffer.byteLength(result) <= maxBytes + Buffer.byteLength(TRUNCATION_MARKER)
 */
function capContent(content: string, maxBytes: number): string {
  if (Buffer.byteLength(content, 'utf8') <= maxBytes) return content;
  // Slice to maxBytes bytes then decode — UTF-8 boundary may leave a partial
  // multi-byte sequence at the end; toString('utf8') replaces it with U+FFFD.
  const truncated = Buffer.from(content, 'utf8').subarray(0, maxBytes).toString('utf8');
  return truncated + TRUNCATION_MARKER;
}

export class EpisodicStore {
  private readonly db: Database.Database;
  private readonly clock: Clock;
  private readonly config: EngineConfig;

  // Prepared statements — compiled once in constructor (never per-call)
  private readonly stmtInsert: Database.Statement;
  private readonly stmtListUnconsolidated: Database.Statement;
  private readonly stmtGetById: Database.Statement;
  /**
   * The sleep pass is the sole writer of episode.consolidated (CONSOL-02/03).
   * Called inside the per-episode transaction so a killed/restarted pass never
   * double-applies strength increments (resumable checkpoint).
   */
  private readonly stmtMarkConsolidated: Database.Statement;

  constructor(db: Database.Database, clock: Clock, config: EngineConfig) {
    this.db = db;
    this.clock = clock;
    this.config = config;

    // ── Prepared statements (all use ? / @named — T-02-SQL) ──────────────────

    this.stmtInsert = db.prepare(`
      INSERT INTO episode (
        id, ts, content, origin, salience, hard_keep,
        consolidated, source_inference_id, role, session_id
      ) VALUES (
        @id, @ts, @content, @origin, @salience, @hard_keep,
        0, @source_inference_id, @role, @session_id
      )
    `);

    // D-03 / D-10: replay priority — hard_keep first, then salience descending
    this.stmtListUnconsolidated = db.prepare(
      'SELECT * FROM episode WHERE consolidated = 0 ORDER BY hard_keep DESC, salience DESC',
    );

    this.stmtGetById = db.prepare('SELECT * FROM episode WHERE id = ?');

    // CONSOL-02/03: sole writer of episode.consolidated; called inside each episode's transaction
    this.stmtMarkConsolidated = db.prepare(
      'UPDATE episode SET consolidated = 1 WHERE id = ?'
    );
  }

  /**
   * Unconditionally insert one episode row and return it.
   * Content is capped at config.maxContentBytes with a truncation marker (D-09).
   * ts is taken from clock.nowMs() — never Date.now() (D-12).
   */
  append(params: AppendEventParams): EpisodeRow {
    const id = newId();
    const ts = this.clock.nowMs();
    const content = capContent(params.content, this.config.maxContentBytes);

    this.stmtInsert.run({
      id,
      ts,
      content,
      origin: params.origin,
      salience: params.salience,
      hard_keep: params.hard_keep,
      source_inference_id: params.source_inference_id ?? null,
      role: params.role,
      session_id: params.session_id,
    });

    // Return the stored row (SELECT is cheaper than trusting the insert params)
    return this.stmtGetById.get(id) as EpisodeRow;
  }

  /**
   * All episodes not yet processed by the sleep pass, in replay-priority order:
   *   hard_keep DESC, then salience DESC (D-03 / D-10).
   * Leverages idx_episode_unconsolidated index.
   */
  listUnconsolidated(): EpisodeRow[] {
    return this.stmtListUnconsolidated.all() as EpisodeRow[];
  }

  /**
   * Retrieve a single episode by id.
   * Returns null if the id does not exist.
   */
  getEpisode(id: string): EpisodeRow | null {
    const row = this.stmtGetById.get(id) as EpisodeRow | undefined;
    return row ?? null;
  }

  /**
   * Mark an episode as consolidated (consolidated = 1).
   * SOLE WRITER of episode.consolidated — only the sleep pass calls this (CONSOL-02/03).
   * Must be called inside the same db.transaction as the episode's strength/graph effects
   * so a killed/restarted pass never double-applies a strength increment.
   */
  markConsolidated(id: string): void {
    this.stmtMarkConsolidated.run(id);
  }
}
