// GENERATED by scripts/gen-simd-kernel.cjs from simd-kernel.wat — DO NOT EDIT BY HAND
// Run `npm run gen:simd-kernel` to regenerate after modifying simd-kernel.wat.

const WASM_BASE64 = 'AGFzbQEAAAABCwFgB39/f399f38AAgwBA2VudgNtZW0CAAEDAgEABwgBBHNjYW4AAAqoAQGlAQIDfwF7QQAhBwJAA0AgByAFTw0BIAEgByAGbGohCf0MAAAAAAAAAAAAAAAAAAAAACEKQQAhCAJAA0AgCCAGTw0BIAogACAIav0ABAAgCSAIav0ABAD95gH95AEhCiAIQRBqIQgMAAsLIAMgB0EEbGogCv0fACAK/R8BkiAK/R8CIAr9HwOSkiACIAdBBGxqKgIAlCAElDgCACAHQQFqIQcMAAsLCw==';

/** Return the raw WASM bytes for the fused f32x4 cosine-scan kernel. */
export function wasmBytes(): Uint8Array {
  return Buffer.from(WASM_BASE64, 'base64');
}
