#!/usr/bin/env bash
# setup-watcher.sh — set up the recense channel watcher service.
#
# What this script does:
#   1. Builds the project (npm run build → dist/) and verifies the watcher CLI exists.
#   2. ADDITIVELY writes RECENSE_WATCHER_JS to ~/.config/recense/sleep.env,
#      preserving all existing lines (API keys, DB path, sleep-pass config, etc.).
#   3. Installs the KeepAlive launchd agent (com.recense.watcher).
#   4. Prints rollback instructions and config reminder.
#
# Idempotent: safe to re-run. Re-running after npm run build updates the watcher JS path.
#
# DO NOT run as root — this installs a user-space LaunchAgent.
# Do NOT enable the channel from this script — edit src/lib/config.ts and rebuild.

set -euo pipefail

# ── Resolve paths ────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Absolute node binary — must be absolute; 'node' may not be on PATH in launchd context.
# Run this script with your target nvm version active (e.g. nvm use <version>).
NODE_BIN="$(command -v node 2>/dev/null || true)"
if [[ -z "$NODE_BIN" ]]; then
    echo "ERROR: node not found on PATH. Activate nvm first: nvm use <version>" >&2
    exit 1
fi
# Follow symlinks to the real binary (nvm may symlink node on some configs)
NODE_BIN="$(cd "$(dirname "$NODE_BIN")" && pwd)/$(basename "$NODE_BIN")"

# Watcher CLI dist path
DIST_ADAPTER="$PROJECT_ROOT/dist/src/adapter"
WATCHER_CLI="$DIST_ADAPTER/watcher-cli.js"

# Env file — the SAME file used by the sleep pass (additive only; no second file)
ENV_FILE="${RECENSE_SLEEP_ENV:-$HOME/.config/recense/sleep.env}"

# Committed, secret-free launchd wrapper (sources the env file, then execs node)
WRAPPER="$SCRIPT_DIR/watcher-launchd.sh"

# launchd plist locations
PLIST_TEMPLATE="$SCRIPT_DIR/com.recense.watcher.plist.template"
LAUNCHAGENTS_DIR="$HOME/Library/LaunchAgents"
PLIST_DST="$LAUNCHAGENTS_DIR/com.recense.watcher.plist"
PLIST_LABEL="com.recense.watcher"

# ── Step 1: Build ─────────────────────────────────────────────────────────────
echo ""
echo "==> [1/4] Building recense..."
cd "$PROJECT_ROOT"
npm run build
echo "    Build complete."
echo ""

# Verify the watcher dist CLI exists after build
if [[ ! -f "$WATCHER_CLI" ]]; then
    echo "ERROR: Expected compiled watcher CLI missing: $WATCHER_CLI" >&2
    echo "       Check tsconfig.json and re-run 'npm run build'." >&2
    exit 1
fi
echo "    Watcher CLI present: $WATCHER_CLI"
echo ""

# ── Step 2: ADDITIVELY update sleep.env (never clobber existing keys) ─────────
echo "==> [2/4] Updating sleep env file (additive — preserves all existing keys)..."
mkdir -p "$(dirname "$ENV_FILE")"

# preserve_key: echoes the last "NAME=..." line from $ENV_FILE if present.
# Used for API key safety verification (mirrors setup-dogfood.sh pattern).
preserve_key() {
    if [[ -f "$ENV_FILE" ]]; then
        grep -E "^${1}=" "$ENV_FILE" | tail -n 1 || true
    fi
}

# Safety check: warn (but do not abort) if API keys would be lost.
# The grep-based preservation below retains ALL existing lines, including API keys.
EXISTING_ANTHROPIC="$(preserve_key ANTHROPIC_API_KEY)"
EXISTING_OPENAI="$(preserve_key OPENAI_API_KEY)"
if [[ -z "$EXISTING_ANTHROPIC" && -z "$EXISTING_OPENAI" ]]; then
    echo "    NOTE: No API key lines found in current env file (will be created fresh)."
fi

# Build the new file content: preserve all existing lines except any prior
# RECENSE_WATCHER_JS entry, then append the new value (idempotent on re-run).
if [[ -f "$ENV_FILE" ]]; then
    FILTERED_CONTENT="$(grep -v '^RECENSE_WATCHER_JS=' "$ENV_FILE" || true)"
else
    FILTERED_CONTENT="# recense env — GITIGNORED, chmod 600. Do NOT commit.
# Generated by setup-watcher.sh; re-run safely to update RECENSE_WATCHER_JS."
fi

# Atomic write with restrictive perms (umask 077 → 600). Key values go to the
# file ONLY — never echoed to stdout. mv makes the write atomic.
TMPFILE="$(mktemp "$(dirname "$ENV_FILE")/sleep.env.XXXXXX")"
(
    umask 077
    {
        printf '%s\n' "$FILTERED_CONTENT"
        printf 'RECENSE_WATCHER_JS=%s\n' "$WATCHER_CLI"
    } > "$TMPFILE"
)
mv "$TMPFILE" "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo "    Env file updated: $ENV_FILE (chmod 600)"
echo "    RECENSE_WATCHER_JS=$WATCHER_CLI"
echo ""

# ── Step 3: Install launchd KeepAlive agent ────────────────────────────────────
echo "==> [3/4] Installing launchd KeepAlive agent..."
mkdir -p "$LAUNCHAGENTS_DIR"

# Render plist template: substitute wrapper path + env-file path
sed \
    -e "s|__WRAPPER__|$WRAPPER|g" \
    -e "s|__ENV_FILE__|$ENV_FILE|g" \
    "$PLIST_TEMPLATE" > "$PLIST_DST"
echo "    Plist written: $PLIST_DST"

# Validate the rendered plist XML
if ! plutil -lint "$PLIST_DST" > /dev/null 2>&1; then
    echo "ERROR: plutil -lint failed on rendered plist. Details:" >&2
    plutil -lint "$PLIST_DST" >&2
    exit 1
fi
echo "    plutil -lint: OK"

# Load via the modern per-user domain API (launchctl load is deprecated on current macOS).
LAUNCHD_DOMAIN="gui/$(id -u)"
launchctl bootout "$LAUNCHD_DOMAIN/$PLIST_LABEL" 2>/dev/null || true
# Clear any stale disabled override — a prior launchctl bootout/disable leaves the label
# flagged disabled, which makes bootstrap fail with errno 5 even with a valid plist.
launchctl enable "$LAUNCHD_DOMAIN/$PLIST_LABEL" 2>/dev/null || true
if launchctl bootstrap "$LAUNCHD_DOMAIN" "$PLIST_DST" 2>/dev/null; then
    echo "    Loaded: $PLIST_LABEL"
    echo "    Verify: launchctl print $LAUNCHD_DOMAIN/$PLIST_LABEL | grep state"
else
    echo "    Could not load from this context (need a GUI login session — not SSH/sandbox)." >&2
    echo "    Run manually:" >&2
    echo "      launchctl bootstrap $LAUNCHD_DOMAIN $PLIST_DST" >&2
fi
echo ""

# ── Step 4: Reminders + rollback ──────────────────────────────────────────────
echo "==> [4/4] Required next steps before the watcher can answer queries:"
echo ""
echo "    ENABLE THE CHANNEL in src/lib/config.ts:"
echo "    For Telegram (recommended):"
echo "      telegram.enable    = true"
echo "      telegram.allowlist = [<your numeric Telegram user ID>]"
echo "    Put your bot token in $ENV_FILE:"
echo "      RECENSE_TELEGRAM_TOKEN=<your-bot-token>"
echo ""
echo "    Then rebuild: npm run build"
echo "    (Re-run this script after rebuilding to pick up the updated dist CLI.)"
echo ""
echo "    NOTE: If using the iMessage channel (advanced, macOS-only), grant Full Disk"
echo "    Access to your node binary so the watcher can read ~/Library/Messages/chat.db."
echo "    Location: System Settings → Privacy & Security → Full Disk Access"
echo "    Add: $NODE_BIN"
echo ""
echo "    ROLLBACK:"
echo "    launchctl bootout $LAUNCHD_DOMAIN/$PLIST_LABEL"
echo "    rm $PLIST_DST"
echo "    (Optional) Remove the RECENSE_WATCHER_JS line from $ENV_FILE"
echo ""
echo "==> Setup complete."
echo "    KeepAlive agent : $PLIST_LABEL"
echo "    Watcher CLI     : $WATCHER_CLI"
echo "    Env file        : $ENV_FILE"
echo "    Node binary     : $NODE_BIN"
echo ""
