#!/usr/bin/env bash
# sleep-pass-launchd.sh — launchd wrapper for the recense hourly sleep pass.
#
# Committed, secret-free. Sources a gitignored env file (keys + per-role config)
# then execs node on the compiled sleep-pass CLI. The env file path is taken from
# RECENSE_SLEEP_ENV (set in the plist) or defaults to
# ~/.config/recense/sleep.env.
#
# The env file is generated by scripts/setup-dogfood.sh (chmod 600) and holds:
#   RECENSE_NODE_BIN, RECENSE_SLEEP_JS, RECENSE_DB,
#   RECENSE_EXTRACTOR_PROVIDER, RECENSE_LOCAL_MODEL,
#   RECENSE_JUDGE_PROVIDER, ANTHROPIC_API_KEY, OPENAI_API_KEY.
set -euo pipefail

ENV_FILE="${RECENSE_SLEEP_ENV:-$HOME/.config/recense/sleep.env}"
if [ -f "$ENV_FILE" ]; then set -a; . "$ENV_FILE"; set +a; fi
exec "${RECENSE_NODE_BIN:-node}" "${RECENSE_SLEEP_JS:?RECENSE_SLEEP_JS not set (check $ENV_FILE)}"
