#!/usr/bin/env bash
# sleep-pass-launchd.sh — launchd wrapper for the brain-memory hourly sleep pass.
#
# Committed, secret-free. Sources a gitignored env file (keys + per-role config)
# then execs node on the compiled sleep-pass CLI. The env file path is taken from
# BRAIN_MEMORY_SLEEP_ENV (set in the plist) or defaults to
# ~/.config/brain-memory/sleep.env.
#
# The env file is generated by scripts/setup-dogfood.sh (chmod 600) and holds:
#   BRAIN_MEMORY_NODE_BIN, BRAIN_MEMORY_SLEEP_JS, BRAIN_MEMORY_DB,
#   BRAIN_MEMORY_EXTRACTOR_PROVIDER, BRAIN_MEMORY_LOCAL_MODEL,
#   BRAIN_MEMORY_JUDGE_PROVIDER, ANTHROPIC_API_KEY, OPENAI_API_KEY.
set -euo pipefail

ENV_FILE="${BRAIN_MEMORY_SLEEP_ENV:-$HOME/.config/brain-memory/sleep.env}"
if [ -f "$ENV_FILE" ]; then set -a; . "$ENV_FILE"; set +a; fi
exec "${BRAIN_MEMORY_NODE_BIN:-node}" "${BRAIN_MEMORY_SLEEP_JS:?BRAIN_MEMORY_SLEEP_JS not set (check $ENV_FILE)}"
